[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"

# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 99

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 100