[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 20

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 30

[[main]]
  name = "Spaces"
  pageRef = "spaces"
  weight = 40

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"



[[footer]]
  name = "Thoughts"
  pageRef = "thoughts"
  weight = 80

[[footer]]
  name = "Changelog"
  pageRef = "Changelog"
  weight = 90

[[footer]]
  name = "Privacy"
  pageRef = "privacy"
  weight = 100